config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments
      resources :likes, only: [:create]
    end 
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, [Post, Comment, Like]

      can %i[update destroy], Post, author_id: user.id
      can %i[update destroy], Comment, author_id: user.id
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :comments_update

  private

  def comments_update
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :likes_update

  private

  def likes_update
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }

  def display_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def display_posts
    posts.order(created_at: :desc).limit(3)
  end

  ROLES = %i[admin default].freeze

  def admin?
    role == 'admin'
  end

  def is?(requested_role)
    self.role = requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  include ApiHelpers
  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @comment = Comment.new
    json_response(@comment)
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:post_id])
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
    json_response(@comments)
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(@post.id, @post)
    else
      # Handle errors if the comment cannot be saved
      render 'posts/show'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to user_post_path(@post.id, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Like.include(:post)
  end

  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(author_id: @user.id, post_id: @post.id)
    return unless @like.save

    redirect_to user_posts_path(@post.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    json_response(@posts)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
    authorize! :create, @post
  end

  def create
    @post = Post.new(post_params)
    @user = User.find(params[:user_id])
    @post.author = current_user
    authorize! :create, @post

    if @post.save
      redirect_to user_post_url(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @post # Ensure user is allowed to edit this post
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.author
    @post.destroy

    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.includes(:posts).all
  end

  def show
    @user = User.includes(posts: %i[comments likes]).find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
    render file: "#{Rails.root}/public/404.html", status: :not_found unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div>
  <p>
    <strong><%= comment.author.name %>:</strong>
    <%= comment.text %>
  </p>
</div>

app/views/comments/new.html.erb
<%= form_with model: [@post, @comment], url: user_post_comments_path( @post) do |form| %>
    <p>
      <%= form.label :text %>
      <%= form.text_field :text, class: 'post_title' %>
    </p>

    <p>
      <%= form.submit 'Submit comment', class: 'post_btn' %>
    </p>
  <% end %>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_user_post_comment_path(@comment) %> |
  <%= link_to "Back to comments", user_post_comments_path(@comment.post.author, @comment.post) %>

  <%= button_to "Destroy this comment", user_post_comment_path(@comment.post.author, @comment.post, @comment), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class='user-show-container'>
<div class='show-box'>
<%= image_tag @user.photo.present? ? @user.photo : 'default.jpg' %>
<div class='profile-box'>
<div class='prof-name'><%= @user.name %></div>
<div class='prof-counter'>No of posts: <%= @user.posts.count %></div>
</div>
</div>

<button class="create-button">
<%= link_to "Create new post", new_user_post_path(@user.id) if can? :create, Post %>
  </button>

<% @posts.each do |post| %>
    <%= link_to user_post_path(@user, post.id), class: 'post-item' do %>
      <div class="post">
        <div>
          <h3><%= post.title %></h3>
          <p><%= post.text.split(" ")[0..80].join(" ") %></p>
        </div>
        <div class="likes-comments">
          <span class="comments">Comments:
            <%= post.comments_counter %>,
          </span>
          <span class="likes">Likes:
            <%= post.likes_counter %></span>
        </div>
      </div>
      <div class="comments-container">
        <% post.display_comments.each do |comment| %>
          <div class="comment">
            <span><%= comment.author.name %>:</span>
            <span><%= comment.text %></span>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="buttons">
  <% if @posts.present? %>
    <button class="pagination">
      <%= link_to "Pagination", user_post_path(@user, @posts.first) %>
    </button>
  <% end %>

  <button class="back-button">
    <%= link_to "Back to all users", root_path %>
  </button>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url: user_posts_path(@user) do |form| %>
  <div class='main-post-form'>
    <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: 'post_title' %>
    </div>
  
    <div>
    <%= form.label :text %><br>
    <%= form.text_area :text,  class: 'post_text' %>
    </div>
  
    <%= form.submit 'Create new post', class: 'post_btn'%>
    </div>
  <% end %>

app/views/posts/show.html.erb
<div class="comments-details">
  <div class="comments-container">
    <div class="posts-title">
      <h2>Post   <%= @post.id %> by <%= @user.name %></h2>
      </div>
    <div class="likes-comments">
      <span class="comments">Comments: <%= @post.comments_counter %>, </span>
      <span class="likes">Likes: <%= @post.likes_counter %></span>
      <!-- app/views/posts/show.html.erb -->
    <% if can? :destroy, @post %>
      <%= button_to "Delete", user_post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    <% end %>

    </div>
    <p><%= @post.text %></p>
    </div>
  </div>

  <div class="comments-container">
    <% @comments = Post.find(@post.id).comments %>
      <% @comments.includes(:author).each do |comment| %>
        <div>
          <span><%= comment.author.name %> : <%= comment.text %></span>
        </div>
        <% if can? :destroy, comment %>
          <%= link_to "Delete", user_post_comment_path(@post.author, @post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
      <% end %>
  </div>
 
  <%= form_with url: "/users/#{@post.author.id}/posts/#{@post.id}/likes" do |form| %>
    <%= form.submit 'Like', class: 'like_btn' %>
    <% end %>

  <button class='back-button'><%= link_to "Add a comment", new_user_post_comment_path(@post.author, @post) %></button>

  <div>
  <button class='back-button'>
      <%= link_to "Back to all users", root_path %>
    </button>
    </div>
</div>

app/views/users/index.html.erb
<div class='main-container'>
<ul>
<% @users.each do |user| %>
    <li class='user-list'>
    <div class="photo"><%= image_tag user.photo.present? ? user.photo : 'default.jpg' %></div>
    <div class='user-box'>
    <div class='name'><%= link_to user.name, user %></div>
    <div class='counter'>No of posts: <%= user.posts.count %></div>
    </div>
    </li>
    <% end %>
</ul>
</div>

app/views/users/show.html.erb
<div class='user-show-container'>
<div class='show-box'>
<%= image_tag @user.photo.present? ? @user.photo : 'default.jpg' %>
<div class='profile-box'>
<div class='prof-name'><%= @user.name %></div>
<div class='prof-counter'>No of posts: <%= @user.posts.count %></div>
</div>
</div>

<div class='bio'>Bio<br>
 <%= @user.bio %>
 </div>

<% @user.display_posts.each do |post| %>
    <div class='show-post'>
<%= link_to user_post_path(@user, post.id) do %>
<div class='show-post-id'>
  <strong>Post:</strong>
  <%= post.id %>
</div>

<div class='show-post-content'>
  <%= post.text %>
</div>

<div class='show-counter'>
  Comments: <%= post.comments.count %>
  Likes: <%= post.likes.count %>
</div>
</div>
<%end%>
<% end %>

<div class='prof-button'>
<%= link_to "See all posts", user_posts_path(@user) %>
</div>
</div>

<div></div>